garden:
  taxonomy:
    - Bloom:
        - Seed
        - Root
        - Soil
    - Rose:
        - Petal
        - Stem
        - Thorn
        - Sepal
    - Orchid
    - Oak:
        - Acorn
        - Branch
        - Leaf
    - Fern
    - Vine
